// Cloudflare Worker entry. `Env` and the runtime globals (Fetcher,
// ExportedHandler, …) are generated by `pnpm cf-typegen` (wrangler types)
// into worker-configuration.d.ts.
//
// This is where @rxjs-full/server + @rxjs-full/cloudflare will plug in:
// turn the incoming Request into an Observable pipeline and stream the Response.

export default {
  async fetch(request, env): Promise<Response> {
    const url = new URL(request.url)

    if (url.pathname.startsWith('/api/')) {
      return Response.json({
        framework: 'rxjs-full-claude',
        message: 'Hello from the Worker runtime 👋',
        path: url.pathname,
      })
    }

    // Everything else: serve the Vite-built client assets (SPA fallback).
    return env.ASSETS.fetch(request)
  },
} satisfies ExportedHandler<Env>
